
POST http://localhost:3000/api/auth/signup
content-type: application/json

{   
    "name":"Vinay2",
    "email":"Vinay2@123",
    "password":"Vinay@123",
    "number": 9876274312
}

###
POST http://localhost:3000/api/auth/signup/verifyOtp
content-type: application/json

{   

    "otp": 143102
}

###

POST http://localhost:3000/api/auth/generateOtp
content-type: application/json

{
    "email": "Vinay@gmail.com"
}

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email":"Vinay@gmail.com",
    "password":"Vinay@123",
}
###

POST http://localhost:3000/api/auth/logout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDViMzQxOTU4ZWI0MDcxOTliODllODUiLCJuYW1lIjoiVmluYXkiLCJlbWFpbCI6IlZpbmF5QGdtYWlsLmNvbSIsImlhdCI6MTY4MzY5ODg0MiwiZXhwIjoxNjgzNzg1MjQyfQ.DhGm_Xwm8UVJoOaRclLkXm5tTCQXmeAgmoCMQflEaWI



// Tags
###
POST http://localhost:3000/api/tag
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDViMzQxOTU4ZWI0MDcxOTliODllODUiLCJuYW1lIjoiVmluYXkiLCJlbWFpbCI6IlZpbmF5QGdtYWlsLmNvbSIsImlhdCI6MTY4MzY5ODg0MiwiZXhwIjoxNjgzNzg1MjQyfQ.DhGm_Xwm8UVJoOaRclLkXm5tTCQXmeAgmoCMQflEaWI

{
    "name":"Machine Learning",
    "description":"This is a tag of ML"

}

###
GET http://localhost:3000/api/tag
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDViMzQxOTU4ZWI0MDcxOTliODllODUiLCJuYW1lIjoiVmluYXkiLCJlbWFpbCI6IlZpbmF5QGdtYWlsLmNvbSIsImlhdCI6MTY4MzY5ODg0MiwiZXhwIjoxNjgzNzg1MjQyfQ.DhGm_Xwm8UVJoOaRclLkXm5tTCQXmeAgmoCMQflEaWI



###
GET http://localhost:3000/api/tag/645b355aeafa3b4422ab6249
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDViMzQxOTU4ZWI0MDcxOTliODllODUiLCJuYW1lIjoiVmluYXkiLCJlbWFpbCI6IlZpbmF5QGdtYWlsLmNvbSIsImlhdCI6MTY4MzY5ODg0MiwiZXhwIjoxNjgzNzg1MjQyfQ.DhGm_Xwm8UVJoOaRclLkXm5tTCQXmeAgmoCMQflEaWI
