
GET http://localhost:3000/
###

GET http://localhost:3000/api/products


###


GET http://localhost:3000/api/v1/notes

###

POST http://localhost:3000/api/user
content-type: application/json

{
    "name": "Vinay",
    "email":"Vinay@gmail.com",
    "password": "Vinay@123"

}


